services:
  postgres:
    image: postgres:18.4-alpine3.24
    container_name: prefect-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect
    volumes:
      - postgres_data:/var/lib/postgresql

  prefect-server:
    image: prefecthq/prefect:sha-05c045c-python3.12
    container_name: prefect-server
    ports:
      - "4200:4200"
    environment:
      - PREFECT_SERVER__DATABASE__CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      - PREFECT_SERVER__TELEMETRY__ENABLED=false
    command: prefect server start --host 0.0.0.0
    depends_on:
      - postgres

  prefect-worker:
    image: ghcr.io/ayano590/vienna-data-platform:latest
    container_name: prefect-worker
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_LOGGING_LEVEL=INFO
    command: prefect worker start --pool default
    depends_on:
      - prefect-server

volumes:
  postgres_data: