services:
  postgres:
    image: postgres:18.4-alpine3.24
    container_name: prefect-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect
    volumes:
      - postgres_data:/var/lib/postgresql

  prefect-server:
    image: prefecthq/prefect:sha-05c045c-python3.12
    container_name: prefect-server
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      - PREFECT_SERVER_ANALYTICS_ENABLED=false
    command: prefect server start --host 0.0.0.0
    depends_on:
      - postgres

  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile.prefect-worker
    container_name: prefect-worker
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_LOGGING_LEVEL=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: prefect worker start --pool docker-work-pool
    depends_on:
      - prefect-server

volumes:
  postgres_data: